name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main
    - dev
    - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        exclude-directories: 'vendor,node_modules'
        exclude-files: '.distignore,.gitignore,.phpcs.xml.dist,composer.json,composer.lock'

  phpcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
        tools: composer

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Run PHPCS
      run: composer run lint